### ISSUE TITLE
Crash on initial load when there is failedItems 

### ISSUE THREAD

**Issue by erlingfjelstad** [dhis2/dhis2-android-trackercapture#54]
If register a tracked entity instance and getting error. When trying to log out and re-log in the app is crashing.
Stack trace:
08-25 10:49:01.521    1605-2221/org.hisp.dhis.android.trackercapture E/AndroidRuntime﹕ FATAL EXCEPTION: ModernAsyncTask #3
    Process: org.hisp.dhis.android.trackercapture, PID: 1605
    java.lang.RuntimeException: An error occured while executing doInBackground()
            at android.support.v4.content.ModernAsyncTask$3.done(ModernAsyncTask.java:137)
            at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
            at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
            at java.util.concurrent.FutureTask.run(FutureTask.java:242)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.hisp.dhis.android.sdk.persistence.models.TrackedEntityInstance.getTrackedEntityInstance()' on a null object reference
            at org.hisp.dhis.android.trackercapture.fragments.selectprogram.SelectProgramFragmentQuery.query(SelectProgramFragmentQuery.java:116)
            at org.hisp.dhis.android.trackercapture.fragments.selectprogram.SelectProgramFragmentQuery.query(SelectProgramFragmentQuery.java:30)
            at org.hisp.dhis.android.sdk.persistence.loaders.DbLoader.loadInBackground(DbLoader.java:89)
            at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:242)
            at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:51)
            at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:40)
            at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:123)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)

**Comment by erlingfjelstad** [comment]
Can't reproduce
