### ISSUE TITLE
QueryTrackedEntityInstancesDialog doesn't appear every time

### ISSUE THREAD

**Issue by erlingfjelstad** [dhis2/dhis2-android-trackercapture#58]

**Comment by erlingfjelstad** [comment]
If you try to click several times on mQueryTEIbutton, this exception occurs:

09-07 11:56:37.826  14209-14209/org.hisp.dhis.android.trackercapture E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: org.hisp.dhis.android.trackercapture, PID: 14209
    java.lang.ClassCastException: android.widget.LinearLayout cannot be cast to org.hisp.dhis.android.sdk.ui.views.FontTextView
            at org.hisp.dhis.android.sdk.ui.dialogs.QueryTrackedEntityInstancesResultDialogAdapter.createViewFromResource(QueryTrackedEntityInstancesResultDialogAdapter.java:131)
            at org.hisp.dhis.android.sdk.ui.dialogs.QueryTrackedEntityInstancesResultDialogAdapter.getView(QueryTrackedEntityInstancesResultDialogAdapter.java:109)
            at android.widget.AbsListView.obtainView(AbsListView.java:2467)
            at android.widget.ListView.measureHeightOfChildren(ListView.java:1270)
            at android.widget.ListView.onMeasure(ListView.java:1182)
            at android.view.View.measure(View.java:17536)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5478)
            at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
            at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
            at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
            at android.view.View.measure(View.java:17536)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5478)
            at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
            at android.view.View.measure(View.java:17536)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5478)
            at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
            at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
            at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
            at android.view.View.measure(View.java:17536)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5478)
            at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2629)
            at android.view.View.measure(View.java:17536)
            at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2102)
            at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1193)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1435)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1106)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6018)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:792)
            at android.view.Choreographer.doCallbacks(Choreographer.java:596)
            at android.view.Choreographer.doFrame(Choreographer.java:557)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:778)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:155)
            at android.app.ActivityThread.main(ActivityThread.java:5696)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1028)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
